<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
<ItemGroup>
    <ProjectReference Include="..\AntiHD.UI\AntiHD.UI.csproj" />
    <ProjectReference Include="..\AntiHD.Shared\AntiHD.Shared.csproj" />
  </ItemGroup>
  
</Project>
